# Generated by Django 3.2.2 on 2021-05-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
    ]
