# Generated by Django 3.2.2 on 2021-05-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_job_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='added_users',
        ),
    ]
